name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: |
        npm install
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:webaverse/world-server.git
        BRANCH: pre-compile
        FOLDER: ./node_modules